### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by srekkas** [Vytax/plugin.video.tv3.lt#1]
Rikiavimas pagal data neaktyvus. Atsidarius kokia nors laida ir norint paziureti naujausia epizoda reikia eiti per visus puslapius i paskutini saraso elementa.
Kodi 16.1 osmc, Rpi2

**Comment by Vytax** [comment]
Sutvarkiau. Dabar turėtų būti naujausi viršuje. 
Dėkui.
